Use logger from controller-runtime/pkg/runtime/log
Using logger from controller-runtime package directly results in
multiple definition of flag `kubeconfig` when run with operator-sdk
test framework because the test framework also defines kubeconfig flag.

error: panic: <tmp-test-filename.test> flag redefined: kubeconfig

Use logger from controller-runtime/pkg/runtime/log to fix the issue.